[common]
name = "marktool"
port = 8080

[proxy]
ServerAddr = "slide.bionovationimc.com"
ServerPort = 7000


[[workspaces]]
name = "测试工程01"
folder = "E:\\go\\src\\yomo\\html\\img"
classdef = "E:\\go\\src\\yomo\\html\\obj.names"

[[workspaces]]
name = "测试工程02"
folder = "F:\\Workdatas\\红细胞标注\\5\\5"
classdef = "F:\\Workdatas\\红细胞标注\\5\\classnames.txt"


