[common]
Name = "marktool-gray"
Port = 8080

[proxy]
ServerAddr = "slide.bionovationimc.com"
ServerPort = 7000


[[workspaces]]
name = "测试工程01"
folder = "F:\\Workdatas\\红细胞标注\\5\\over0803"
classdef = "F:\\Workdatas\\红细胞标注\\5\\classnames.txt"

[[workspaces]]
name = "测试工程02"
folder = "F:\\Workdatas\\红细胞标注\\5\\5"
classdef = "F:\\Workdatas\\红细胞标注\\5\\classnames.txt"


